### ISSUE TITLE
404 error logging in

### ISSUE THREAD

**Issue by jbedo** [javabean/iNotes-exporter#10]
I'm trying to use iNotes-exporter with iNotes 8.5.3 FP6 but am getting a 404 Not Found error while authenticating.  Any suggestions on how to resolve this?

**Comment by javabean** [comment]
Hi Justin,

You can try to set the `fr.cedrik.inotes.Session` logger in file `src/main/resources/simplelogger.properties` to `debug` or `trace` to know which URL is not found:

```
org.slf4j.simpleLogger.log.fr.cedrik.inotes.Session=debug
```

You will then need to compare the computed URLs with the ones used by your webmail (using e.g. Fiddler or Charles Proxy).

Should you need more assistance, I would advise you do not publicly expose your webmail data in this ticket, and send necessary information by email. We will then work out what's not working properly.

Regards,
Cédrik

**Comment by jbedo** [comment]
Hi Cédrik,

Thanks, I was able to track down the problem.  Seems dwaredirect.nsf has been renamed iwaredir.nsf and after patching that things are working perfectly!  Thanks for your help and for this really useful tool.

Justin
