### ISSUE TITLE
Messed up Date =)

### ISSUE THREAD

**Issue by kalw** [javabean/iNotes-exporter#8]
Hi there,

regarding the "fecth from date" facility, i'm facing a strange behavior :

1/ i fetch all mails once
2/ i look @ the last mail arrival date
3/ i fetch once more with date args, corresponding to the date in point 2

the result is : 

1/ next mail appended to file is actually more or less two hours behind the date in args
2/ mail date is shifted two hours before it's real date of arrival

Regards,
## 

Regis A. Despres

**Comment by javabean** [comment]
This sounds like a TimeZone problem…
I will re-work the incremental export soon. Stay tuned! :-)

**Comment by javabean** [comment]
The incremental export is now fully automatic, and does not need you to specify a start date anymore.

**Comment by kalw** [comment]
Yay ! On the way to test this one.
I'll keep you updated =]

Cdt,

## 

Regis A. Despres
